create table if not exists public.fp_posts (
  id bigint generated by default as identity primary key,
  type text not null,
  title text not null,
  category text not null,
  author text not null default 'admin',
  tags text[] not null default array[]::text[],
  description text not null default '',
  media_url text not null,
  download_url text,
  web_view_url text,
  storage_provider text not null default 'google_drive',
  drive_file_id text,
  storage_path text,
  ratio text not null default '4/5',
  attachments jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now()
);

alter table public.fp_posts drop constraint if exists fp_posts_category_check;
alter table public.fp_posts add column if not exists attachments jsonb not null default '[]'::jsonb;

create table if not exists public.fp_settings (
  key text primary key,
  value text not null,
  updated_at timestamptz not null default now()
);

create table if not exists public.fp_comments (
  id bigint generated by default as identity primary key,
  post_id bigint not null references public.fp_posts(id) on delete cascade,
  author text not null default 'visitor',
  text text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.fp_member_codes (
  code_number text primary key,
  branch text not null,
  is_active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.fp_members (
  id bigint generated by default as identity primary key,
  code_number text not null unique references public.fp_member_codes(code_number),
  branch text not null,
  password_hash text not null,
  password_salt text not null,
  created_at timestamptz not null default now(),
  last_login_at timestamptz
);

alter table public.fp_posts enable row level security;
alter table public.fp_comments enable row level security;
alter table public.fp_settings enable row level security;
alter table public.fp_member_codes enable row level security;
alter table public.fp_members enable row level security;

drop policy if exists "Public can read fp posts" on public.fp_posts;
drop policy if exists "Public can create fp posts" on public.fp_posts;
drop policy if exists "Public can delete fp posts" on public.fp_posts;
drop policy if exists "Signed in users can read fp posts" on public.fp_posts;
drop policy if exists "Public can read fp comments" on public.fp_comments;
drop policy if exists "Public can create fp comments" on public.fp_comments;
drop policy if exists "Signed in users can read fp comments" on public.fp_comments;
drop policy if exists "Signed in users can create fp comments" on public.fp_comments;

create policy "Signed in users can read fp posts"
on public.fp_posts for select
to authenticated
using (true);

create policy "Signed in users can read fp comments"
on public.fp_comments for select
to authenticated
using (true);

create policy "Signed in users can create fp comments"
on public.fp_comments for insert
to authenticated
with check (true);

grant usage on schema public to anon, authenticated;
grant select on public.fp_posts to authenticated;
grant select, insert on public.fp_comments to authenticated;
grant usage, select on all sequences in schema public to authenticated;
revoke all on public.fp_settings from anon, authenticated;
revoke all on public.fp_member_codes from anon, authenticated;
revoke all on public.fp_members from anon, authenticated;
